name: suitmedia_internship
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.2.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  http: ^1.1.2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
